const PIANO_ENUM = {
    48: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.C3.aiff",
    49: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Db3.aiff",
    50: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.D3.aiff",
    51: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Eb3.aiff",
    52: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.E3.aiff",
    53: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.F3.aiff",
    54: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Gb3.aiff",
    54: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.G3.aiff",
    55: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Ab3.aiff",
    56: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.A3.aiff",
    57: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Bb3.aiff",
    58: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.B3.aiff",
    59: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.C4.aiff",
    60: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Db4.aiff",
    61: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.D4.aiff",
    62: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Eb4.aiff",
    63: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.E4.aiff",
    64: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.F4.aiff",
    65: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Gb4.aiff",
    66: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.G4.aiff",
    67: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Ab4.aiff",
    68: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.A4.aiff",
    69: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Bb4.aiff",
    70: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.B4.aiff",
    71: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.C5.aiff",
    72: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Db5.aiff",
    73: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.D5.aiff",
    74: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.Eb5.aiff",
    75: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.E5.aiff",
    76: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.F5.aiff",
    77: "C:/Users/tchur/Desktop/Piano Sounds/piano.ff.F5.aiff",
}

module.exports = PIANO_ENUM;